### ISSUE TITLE
All fields in meta files outside sandbox always empty

### ISSUE THREAD

**Issue by iwanbk** [g8os/fs#7] opened 2016-03-09 04:40 UTC
example
```
Hash = ""
Size = 0
UserKey = ""
StoreKey = ""
```

**Comment by muhamadazmy** [comment] 2016-03-09 06:09
Can you give me more details ? how the meta files ended outside the backend sandbox?

**Comment by muhamadazmy** [comment] 2016-03-09 06:16
The details I need are:
1- The mount mode (rw, ro, ol)
2- The operations the generated this meta file.

**Comment by iwanbk** [comment] 2016-03-09 06:38
1. mount mode = OL
2. 
settings:
```
backend.path = /root/empty
mount.path = /opt
```
steps
```
# cd /opt/
# echo "test" > test.txt
# cat /root/empty/test.txt.meta 
Hash = ""
Size = 0
UserKey = ""
StoreKey = ""
```

**Comment by zaibon** [comment] 2016-03-21 06:52
What's the status on this one ? @iwanbk

**Comment by iwanbk** [comment] 2016-03-21 07:10
@zaibon actually i didn't made further check.

Let me know the expected behaviours, i can try to fix it.

**Comment by muhamadazmy** [comment] 2016-03-22 06:49
@zaibon @iwanbk 
This is actually by design

the meta data file is not only used for the data written inside it (hash, size, etc...)
the data inside is only useful to fetch the file from the store (if it actually exists on the store)

but it also used as a place holder for the file name, and keeps track of the state of the file (modified, deleted, etc...) (using the perm bits as I described before)

When you create a file in OL mode, we create the empty metafile correct flags bits (file modified). of course the file content is useless, but the perm bits are important.

if the metafile was not created, it means any store update later on that has a file with the same path will override the file you created yourself, which is not what we want the existance of the meta file with the correct flags will prevent this from happening.

the empty metafile must stay.

**Comment by muhamadazmy** [comment] 2016-03-22 06:56
Same approach is done for directories. When you create directories in OL mode, also an empty metafile is generated to keep track of the directory name, in case you renamed or deleted the directory afterwards.

Imagine this situation.
in OL mode you populated your backend with an flist that has the following struct
/test.txt/
/dir/another.txt

now, in OL mode you deleted director `dir`.
If you restarted your file system, the directory with it's content will be restored. Which is not what you want!.
So instead of just deleting the dir from the backend we do the following
for every child node of the `dir` we mark the metafile as deleted. we also create an empty metafile for the directory in deleted state.

When the filesystem is restarted, the files/directories that are marked as deleted will not get restored.

If you again did something like `mkdir dir` the meta file of the directory will be touched as `modified` which will make the dir pop back to existence but not the child contents (still have their metafiles marked as deleted)

which is the expected behavior when you delete a dir and then make another one with the same name on a normal filesystem.

**Comment by grimpy** [comment] 2016-03-27 14:11
@muhamadazmy can this be closed

**Comment by muhamadazmy** [comment] 2016-03-30 07:29
yes

**Closed by muhamadazmy** 2016-03-30 07:29 UTC
