### ISSUE TITLE
When deleting file, meta file is not deleted

### ISSUE THREAD

**Issue by iwanbk** [g8os/fs#8] opened 2016-03-09 04:40 UTC

**Comment by muhamadazmy** [comment] 2016-03-09 06:12
That's not a bug.

Meta files are not deleted because if you deleted it, and then restarted the filesystem, the meta data file will be replaced and will restore the file.

Instead the meta files are marked as deleted by setting the perm `x` flag. which marks deletion of the file, then the file will not be listed in normal directly listing and also will not get restored if you restarted the filesystem

**Closed by muhamadazmy** 2016-03-09 06:12 UTC
